import os
import uuid
import json
import re
from datetime import datetime, timezone

from dotenv import load_dotenv
from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq

load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

LOG_FILE = "audit_log.json"

def read_log():
    if not os.path.exists(LOG_FILE):
        return []
    with open(LOG_FILE, "r") as f:
        return json.load(f)

def write_log(entries):
    with open(LOG_FILE, "w") as f:
        json.dump(entries, f, indent=2)

def append_log(entry):
    entries = read_log()
    entries.append(entry)
    write_log(entries)

# --- Signal 1: LLM classification via Groq ---
def llm_signal(text):
    prompt = f"""You are an expert at detecting whether text was written by a human or generated by AI.

Analyze the following text and return ONLY a JSON object with this exact format:
{{"ai_probability": 0.85, "reasoning": "brief explanation"}}

The ai_probability should be a float between 0.0 (definitely human) and 1.0 (definitely AI).
Consider: sentence uniformity, vocabulary diversity, stylistic consistency, natural imperfections, emotional authenticity.

Text to analyze:
\"\"\"{text}\"\"\"

Return ONLY the JSON object, no other text."""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
    )
    raw = response.choices[0].message.content.strip()
    # Strip markdown fences if present
    raw = re.sub(r"```json|```", "", raw).strip()
    result = json.loads(raw)
    return float(result["ai_probability"]), result.get("reasoning", "")

# --- Signal 2: Stylometric heuristics ---
def stylometric_signal(text):
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    if len(sentences) < 2:
        return 0.5  # not enough data

    words_per_sentence = [len(s.split()) for s in sentences]
    avg_len = sum(words_per_sentence) / len(words_per_sentence)
    variance = sum((l - avg_len) ** 2 for l in words_per_sentence) / len(words_per_sentence)

    all_words = text.lower().split()
    total_words = len(all_words)
    unique_words = len(set(all_words))
    ttr = unique_words / total_words if total_words > 0 else 0.5

    punct_count = sum(1 for c in text if c in '.,;:!?-—()[]"\'')
    punct_density = punct_count / total_words if total_words > 0 else 0

    # AI text: low variance, moderate-high TTR, moderate punctuation
    # Human text: high variance, variable TTR, irregular punctuation
    variance_score = max(0, 1 - (variance / 50))   # high variance → low score (more human)
    ttr_score = 1 - min(ttr * 1.2, 1.0)            # very high TTR → slightly more AI
    punct_score = max(0, 1 - (punct_density * 5))  # sparse punctuation → more AI

    ai_probability = (variance_score * 0.5) + (ttr_score * 0.3) + (punct_score * 0.2)
    return round(min(max(ai_probability, 0.0), 1.0), 3)

# --- Confidence scoring ---
def combine_signals(llm_score, stylo_score):
    combined = (llm_score * 0.65) + (stylo_score * 0.35)
    return round(combined, 3)

# --- Transparency label ---
def generate_label(confidence):
    if confidence >= 0.75:
        return (
            f"⚠️ This content shows strong indicators of AI generation "
            f"(confidence: {int(confidence*100)}%). This assessment is automated "
            f"and may not be fully accurate. If you believe this is incorrect, "
            f"you may submit an appeal."
        )
    elif confidence <= 0.35:
        return (
            f"✅ This content shows strong indicators of human authorship "
            f"(confidence: {int((1-confidence)*100)}%). Our system found natural "
            f"variation and stylistic patterns consistent with human writing."
        )
    else:
        return (
            f"❓ Our system is uncertain about the origin of this content "
            f"(AI likelihood: {int(confidence*100)}%). The writing shows mixed signals. "
            f"Human and AI-assisted content can both appear here. "
            f"The creator may submit an appeal to provide more context."
        )

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json()
    if not data or "text" not in data or "creator_id" not in data:
        return jsonify({"error": "Missing required fields: text, creator_id"}), 400

    text = data["text"]
    creator_id = data["creator_id"]
    content_id = str(uuid.uuid4())

    llm_score, llm_reasoning = llm_signal(text)
    stylo_score = stylometric_signal(text)
    confidence = combine_signals(llm_score, stylo_score)

    if confidence >= 0.75:
        attribution = "likely_ai"
    elif confidence <= 0.35:
        attribution = "likely_human"
    else:
        attribution = "uncertain"

    label = generate_label(confidence)

    entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "llm_reasoning": llm_reasoning,
        "stylo_score": stylo_score,
        "status": "classified",
        "appeal": None,
    }
    append_log(entry)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylo_score": stylo_score,
        "label": label,
        "status": "classified",
    })

@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json()
    if not data or "content_id" not in data or "creator_reasoning" not in data:
        return jsonify({"error": "Missing required fields: content_id, creator_reasoning"}), 400

    content_id = data["content_id"]
    reasoning = data["creator_reasoning"]

    entries = read_log()
    matched = False
    for entry in entries:
        if entry["content_id"] == content_id:
            entry["status"] = "under_review"
            entry["appeal"] = {
                "submitted_at": datetime.now(timezone.utc).isoformat(),
                "creator_reasoning": reasoning,
            }
            matched = True
            break

    if not matched:
        return jsonify({"error": "content_id not found"}), 404

    write_log(entries)
    return jsonify({
        "content_id": content_id,
        "status": "under_review",
        "message": "Your appeal has been received and logged. A human reviewer will assess it.",
    })

@app.route("/log", methods=["GET"])
def get_log():
    entries = read_log()
    return jsonify({"entries": entries[-20:]})  # return last 20

if __name__ == "__main__":
    app.run(debug=True)
